# fly.toml app configuration file generated for haystack on 2024-09-05T18:52:53+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haystack'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
